namespace :docker do
  desc "Build The Case of the Unused Methods"
  task :build do
    sh "docker build -t peeking_into_ruby/unused_methods ."
  end

  desc "Run The Case of the Unused Methods"
  task :run do
    sh "docker run -it peeking_into_ruby/unused_methods:latest bash"
  end
end
