namespace :docker do
  desc "Build The Case of the Occasional Lag"
  task :build do
    sh "docker build -t peeking_into_ruby/occasional_lag ."
  end

  desc "Run The Case of the Occasional Lag"
  task :run do
    sh "docker run --privileged -it peeking_into_ruby/occasional_lag:latest bash"
  end
end
