namespace :docker do
  desc "Build The Case of the Mysterious Hang"
  task :build do
    sh "docker build -t peeking_into_ruby/mysterious_hang ."
  end

  desc "Run The Case of the Mysterious Hang"
  task :run do
    sh "docker run --privileged -it peeking_into_ruby/mysterious_hang:latest bash"
  end
end
