namespace :docker do
  desc "Build The Case of the Missing Config"
  task :build do
    sh "docker build -t peeking_into_ruby/missing_config ."
  end

  desc "Run The Case of the Missing Config"
  task :run do
    sh "docker run --privileged -it peeking_into_ruby/missing_config:latest bash"
  end
end
